### ISSUE TITLE
NOVA 4 SECURITY ISSUE: no authenticate middleware on log-tool routes

### ISSUE THREAD

**Issue by wjstraver** [KABBOUCHI/nova-logs-tool#48]
Hi,

After another pentest with using Nova 4, we noticed we could download the log files **without being logged in**.

After some digging, I noticed the `config/nova.php` part for middleware has changed from:

```php
return [
    //..
    'middleware' => [
        'web',
        Authenticate::class,
        DispatchServingNovaEvent::class,
        BootTools::class,
        Authorize::class,
    ],
    //..
];
```

to

```php
return [
    //..
    'middleware' => [
        'web',
        HandleInertiaRequests::class,
        DispatchServingNovaEvent::class,
        BootTools::class,
    ],

    'api_middleware' => [
        'nova',
        Authenticate::class,
        Authorize::class,
    ],
    //..
];
```

In the `LogsToolServiceProvider.php`, you are using the following to register the routes for the package:
```php

        Nova::router(['nova', Authorize::class], 'logs-tool')
            ->group(__DIR__.'/../routes/inertia.php');

        Route::middleware(['nova', Authorize::class])
            ->prefix('nova-vendor/KABBOUCHI/logs-tool')
            ->group(__DIR__.'/../routes/api.php');
```

This means when upgrading from Nova 3 to Nova 4, the `Authenticate::class` middleware is no longer registered for the routes of this package!

Anyone who knows the url `/nova-vendor/KABBOUCHI/logs-tool/logs/laravel.log` can download the file without being logged in!

Please add the correct middleware to the routes!

**Comment by KABBOUCHI** [comment]
@wjstraver can you submit a PR?

**Comment by wjstraver** [comment]
let me check for the best solution. I guess it will be to change to the nova api middleware, but in that case this update will be only for nova 4 or above

**Comment by KABBOUCHI** [comment]
[nova-logs-tool](https://github.com/KABBOUCHI/nova-logs-tool) v2 is for nova 4 only, don't worry about nova 3
